### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by danboid** [MiSTer-devel/ZXNext_MISTer#14]
If there are any missing features or known bugs with this core then I'd like to see them listed in the README as a TODO / planned features section, or maybe have these listed in a separate document but linked to from the README?

Are there any notable missing features or bugs?

**Comment by sorgelig** [comment]
Port wasn't updated long time.
Need some one really interesting in this core to port new versions.

Generally speaking i don't see much use of this core. ZX Spectrum core is much better. ZX Spectrum core doesn't need VHD file, so it's much easier to add new games.
ZX Next is more a fantasy computer useful only for its own games.

**Comment by cwscws** [comment]
There are many great games for the Next and there will be a lot more in future. And as it’s fully compatible to regular zx it’s a valuable core. I think at least the option for narrower borders like in the zx core and support for latest firmware so that’s compatible to the latest games would be cool.

**Comment by FalafellGB** [comment]
Can we just have a update to support 3.2.0 ?

**Comment by albconde** [comment]
Core update to 3.02  ( last version ) , no new features expected .
